var data = '[{1: { "main_word" : "Weapon", "words" : {"green1": "Sword", "green2": "Gun","green3": "Knife", '
+ '"red1": "Salt", "red2": "River", "red3": "Apple", "red4": "Black", "red5": "Song", "red6": "Bear", "red7": "Engine"}},'
+'2: { "main_word" : "Winter", "words" : {"green1": "Snow", "green2": "Holiday","green3": "Christmas Tree", '
+ '"red1": "Blood", "red2": "Glass", "red3": "Ceremony", "red4": "Steam", "red5": "Bread", "red6": "Cat", "red7": "Veteran"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'4: { "main_word" : "Idea", "words" : {"green1": "Light bulb", "green2": "Eureka","green3": "Thought", '
+ '"red1": "Combine", "red2": "Deputy", "red3": "Cash", "red4": "Tidy", "red5": "Worker", "red6": "Addicted", "red7": "Tolerate"}},'
+'5: { "main_word" : "Life", "words" : {"green1": "Birth", "green2": "Meaning","green3": "Death", '
+ '"red1": "Text", "red2": "Offend", "red3": "Invite", "red4": "Layout", "red5": "Justify", "red6": "Dictate", "red7": "Theorist"}},'
+'6: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'+'3: { "main_word" : "Sun", "words" : {"green1": "Warmth", "green2": "Ray","green3": "Shine", '
+ '"red1": "Tender", "red2": "User", "red3": "Progress", "red4": "Command", "red5": "Play", "red6": "Fox", "red7": "Tongue"}},'
}]';